# Generated by Django 5.0.3 on 2024-04-04 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0002_claims_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="claims",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("IN_PROGRESS", "In progress"),
                    ("REJECTED", "Rejected"),
                    ("APPROVED", "Approved"),
                ],
                default="OPEN",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="claimslogs",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="claims.claims",
            ),
        ),
    ]
